// REGISTER
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

// LOGIN
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

// GET USER
export const GET_USER_REGISTER_REQUEST = "GET_USER_REGISTER_REQUEST";
export const GET_USER_REGISTER_SUCCESS = "GET_USER_REGISTER_SUCCESS";
export const GET_USER_REGISTER_FAILURE = "GET_USER_REGISTER_FAILURE";

// GET ALL USERS
export const GET_ALL_USER_REGISTER_REQUEST = "GET_ALL_USER_REGISTER_REQUEST";
export const GET_ALL_USER_SUCCESS = "GET_ALL_USER_SUCCESS";
export const GET_ALL_USER_FAILURE = "GET_ALL_USER_FAILURE";

// DELETE ADDRESS
export const DELETE_ADDRESS_REQUEST = "DELETE_ADDRESS_REQUEST";
export const DELETE_ADDRESS_SUCCESS = "DELETE_ADDRESS_SUCCESS";
export const DELETE_ADDRESS_FAILURE = "DELETE_ADDRESS_FAILURE";

// UPDATE ADDRESS
export const UPDATE_ADDRESS_REQUEST = "UPDATE_ADDRESS_REQUEST";
export const UPDATE_ADDRESS_SUCCESS = "UPDATE_ADDRESS_SUCCESS";
export const UPDATE_ADDRESS_FAILURE = "UPDATE_ADDRESS_FAILURE";

//  RESET ADDRESS UPDATE STATUS
export const RESET_ADDRESS_UPDATE_SUCCESS = "RESET_ADDRESS_UPDATE_SUCCESS";

// LOGOUT
export const LOGOUT = "LOGOUT";
