// GET ORDERS
export const GET_ORDERS_REQUEST = "GET_ORDERS_REQUEST";
export const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS";
export const GET_ORDERS_FAILURE = "GET_ORDERS_FAILURE";

// GET ORDER BY ID
export const GET_ADMIN_ORDER_BY_ID_REQUEST = "GET_ADMIN_ORDER_BY_ID_REQUEST";
export const GET_ADMIN_ORDER_BY_ID_SUCCESS = "GET_ADMIN_ORDER_BY_ID_SUCCESS";
export const GET_ADMIN_ORDER_BY_ID_FAILURE = "GET_ADMIN_ORDER_BY_ID_FAILURE";

// DELETE ORDER
export const DELETE_ORDER_REQUEST = "DELETE_ORDER_REQUEST";
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS";
export const DELETE_ORDER_FAILURE = "DELETE_ORDER_FAILURE";

// PLACE ORDER
export const PLACE_ORDER_REQUEST = "PLACE_ORDER_REQUEST";
export const PLACE_ORDER_SUCCESS = "PLACE_ORDER_SUCCESS";
export const PLACE_ORDER_FAILURE = "PLACE_ORDER_FAILURE";

// CONFIRM ORDER
export const CONFIRM_ORDER_REQUEST = "CONFIRM_ORDER_REQUEST";
export const CONFIRM_ORDER_SUCCESS = "CONFIRM_ORDER_SUCCESS";
export const CONFIRM_ORDER_FAILURE = "CONFIRM_ORDER_FAILURE";

// SHIP ORDER
export const SHIP_ORDER_REQUEST = "SHIP_ORDER_REQUEST";
export const SHIP_ORDER_SUCCESS = "SHIP_ORDER_SUCCESS";
export const SHIP_ORDER_FAILURE = "SHIP_ORDER_FAILURE";

// OUT FOR DELIVERY ORDER
export const OUT_FOR_DELIVERY_ORDER_REQUEST = "OUT_FOR_DELIVERY_ORDER_REQUEST";
export const OUT_FOR_DELIVERY_ORDER_SUCCESS = "OUT_FOR_DELIVERY_ORDER_SUCCESS";
export const OUT_FOR_DELIVERY_ORDER_FAILURE = "OUT_FOR_DELIVERY_ORDER_FAILURE";

// DELIVER ORDER
export const DELIVER_ORDER_REQUEST = "DELIVER_ORDER_REQUEST";
export const DELIVER_ORDER_SUCCESS = "DELIVER_ORDER_SUCCESS";
export const DELIVER_ORDER_FAILURE = "DELIVER_ORDER_FAILURE";

// CANCEL ORDER
export const CANCEL_ORDER_REQUEST = "CANCEL_ORDER_REQUEST";
export const CANCEL_ORDER_SUCCESS = "CANCEL_ORDER_SUCCESS";
export const CANCEL_ORDER_FAILURE = "CANCEL_ORDER_FAILURE";
